"""create tables

Revision ID: 464786e207ef
Revises: 
Create Date: 2023-09-13 18:09:25.014009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '464786e207ef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('person')
    # ### end Alembic commands ###
